<a href="https://colab.research.google.com/github/kalpnaponnuswamy/inceptez_Assignments/blob/main/LinearRegression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score

In [ ]:
x = [1,3,4,6]
y = [1,2,5,6]


In [ ]:
X = np.array(x)
y = np.array(y)

In [ ]:
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
y_pred = model.predict(X)

In [ ]:
y_pred

array([[0.80769231],
       [2.96153846],
       [4.03846154],
       [6.19230769]])

In [ ]:
mean_squared_error (y, y_pred)

0.4807692307692307

In [ ]:
mean_absolute_error(y, y_pred)

0.5769230769230766

In [ ]:
r2_score(y,y_pred)

0.8868778280542986

In [ ]:
model.coef_

array([[1.07692308]])

In [ ]:
model.intercept_

array([-0.26923077])