In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score

In [2]:
x = [1,3,4,6]
y = [1,2,5,6]


In [3]:
X = np.array(x)
y = np.array(y)

In [4]:
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

In [5]:
model = LinearRegression()

In [6]:
model.fit(X,y)

LinearRegression()

In [7]:
y_pred = model.predict(X)

In [8]:
y_pred

array([[0.80769231],
       [2.96153846],
       [4.03846154],
       [6.19230769]])

In [9]:
mean_squared_error (y, y_pred)

0.4807692307692306

In [10]:
mean_absolute_error(y, y_pred)

0.5769230769230762

In [11]:
r2_score(y,y_pred)

0.8868778280542987

In [12]:
model.coef_

array([[1.07692308]])

In [13]:
model.intercept_

array([-0.26923077])